create table bank_card
(
    bank_card_id  int8 generated by default as identity,
    card_number   int4 not null,
    name_card     varchar(255),
    my_list_ac_id int8,
    primary key (bank_card_id)
);
create table comparator_table
(
    compar_id       int8 generated by default as identity,
    compar_name     varchar(255),
    text_comparator TEXT,
    primary key (compar_id)
);
create table my_list_ac
(
    my_list_ac_id int8 generated by default as identity,
    name_ac       varchar(255),
    account_id    int8,
    primary key (my_list_ac_id)
);
create table role_table
(
    id   int8 generated by default as identity,
    name varchar(255) unique,
    primary key (id)
);
create table user_table
(
    account_id int8 generated by default as identity,
    login      varchar(255),
    password   varchar(255),
    role_id    int8,
    primary key (account_id)
);
create table user_table_my_list_ac
(
    account_account_id       int8 not null,
    my_list_ac_my_list_ac_id int8 not null
);
alter table if exists user_table_my_list_ac
    add constraint my_list_ac_my_list_ac_id1 unique (my_list_ac_my_list_ac_id);
alter table if exists bank_card
    add constraint my_list_ac_id2 foreign key (my_list_ac_id) references my_list_ac;
alter table if exists my_list_ac
    add constraint account_id3 foreign key (account_id) references user_table;
alter table if exists user_table
    add constraint role_id4 foreign key (role_id) references role_table;
alter table if exists user_table_my_list_ac
    add constraint my_list_ac_my_list_ac_id5 foreign key (my_list_ac_my_list_ac_id) references my_list_ac;
alter table if exists user_table_my_list_ac
    add constraint account_account_id6 foreign key (account_account_id) references user_table;
